name: LinearB Deploy Time
description: On successful deployment records the time at which deployment completed
author: https://github.com/cultureamp
requirements:
  - aws
configuration:
  properties:
    sha:
      type: string
    repo:
      type: string
    api_key:
      type: string
    api_key_ssm_param_name:
      type: string
  additionalProperties: false
